services:
  - type: web
    name: portfolio-michael
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: GMAIL_APP_PASSWORD
        sync: false